39 add takeover action
gii-is-DP1/new-corp-order-l2-1 pull request #47
Opened 2023-10-26 20:30 UTC by JustZambetti

2023-10-27 09:40 UTC, mimbrero requested changes

2023-10-27 09:40 UTC, mimbrero commented on src/main/java/us/lsi/dp1/newcorporder/match/Match.java
> +    private Headquarter currentHq;
No es necesario, se puede acceder con `currentTurnPlayer.getHeadquarter()`

2023-10-27 09:40 UTC, mimbrero commented on src/test/java/us/lsi/dp1/newcorporder/achievement/AchievementControllerTest.java
No pongáis esta clase en esta rama (esta rama trata sobre add takeover action)

2023-10-27 10:16 UTC, JustZambetti commented on src/main/java/us/lsi/dp1/newcorporder/match/Match.java
> +    private Headquarter currentHq;
es necesario para la legibilidad del codigo

2023-10-27 15:47 UTC, mimbrero commented
Porfa, utilizad convenciones de Java y no de C# XD

2023-10-30 12:29 UTC, MarcoAnarmo requested changes

2023-10-30 12:29 UTC, MarcoAnarmo commented on src/main/java/us/lsi/dp1/newcorporder/payload/request/CompanyAbilityRequest.java
> +    private CompanyAbility companyAbility;
La `companyAbility` no puede ser `null`.

2023-10-30 12:29 UTC, MarcoAnarmo commented on src/main/java/us/lsi/dp1/newcorporder/payload/request/CompanyAbilityRequest.java
> +@Getter
La anotación `Data` incluye a `Getter`, es innecesario.

2023-10-30 12:29 UTC, MarcoAnarmo commented on src/main/java/us/lsi/dp1/newcorporder/payload/request/ConsultantRequest.java
> +@Getter
La anotación `Data` incluye a `Getter`, es innecesario.

2023-10-30 12:29 UTC, MarcoAnarmo commented on src/main/java/us/lsi/dp1/newcorporder/payload/request/TakeOverRequest.java
> +@Getter
La anotación `Data` incluye a `Getter`, es innecesario.

2023-10-30 12:29 UTC, MarcoAnarmo commented on src/main/java/us/lsi/dp1/newcorporder/payload/request/TakeOverRequest.java
> +    private CompanyTile targetCompany;
Todas estas propiedades no pueden ser `null`.

2023-10-30 12:29 UTC, MarcoAnarmo commented on src/main/java/us/lsi/dp1/newcorporder/match/TakeOver.java
> +        Preconditions.checkState(turnSystem.getCurrentState() == MatchTurnState.TAKING_OVER, "must be in the current state!");
```suggestion
        Preconditions.checkState(turnSystem.getCurrentState() == MatchTurnState.TAKING_OVER, "must be in the current state!");
        takeOverRequest = request;
```

Se os ha olvidado asignarlo y os va a dar `NullPointerException`.

2023-10-30 12:29 UTC, MarcoAnarmo commented on src/main/java/us/lsi/dp1/newcorporder/match/TakeOver.java
> +
intros feos :(

2023-10-30 12:29 UTC, MarcoAnarmo commented on src/main/java/us/lsi/dp1/newcorporder/match/TakeOver.java
> +            //TODO use addShareToHand method
Este método está hecho en la rama `main` en la clase `MatchPlayer`, tenéis que mergearla a vuestra rama y lo incluís.

2023-10-30 12:29 UTC, MarcoAnarmo commented on src/main/java/us/lsi/dp1/newcorporder/match/TurnSystem.java
Usad las convenciones Java que seguís usando las de C# de vez en cuando xd

2023-10-30 12:29 UTC, MarcoAnarmo commented on src/main/java/us/lsi/dp1/newcorporder/match/company/CompanyTile.java
> +    @Setter
¿Dónde estáis llamando a los setters desde fuera de la clase? Lo mejor es modificarlos en los métodos de la misma clase para evitar exponerlos y que se puedan modificar sin control.

2023-10-30 12:29 UTC, MarcoAnarmo commented on src/main/java/us/lsi/dp1/newcorporder/match/player/Headquarter.java
> +    {
Convención C# de nuevo xdd

2023-10-30 12:29 UTC, MarcoAnarmo commented on src/main/java/us/lsi/dp1/newcorporder/match/player/Headquarter.java
> +
Intros feos xddddddd

2023-10-30 12:29 UTC, MarcoAnarmo commented on src/test/java/us/lsi/dp1/newcorporder/achievement/AchievementControllerTest.java
Este test borradlo que es de achievements. Cuando nos pongamos con los tests se pone en una rama más apropiada.

2023-10-31 13:26 UTC, JustZambetti commented on src/main/java/us/lsi/dp1/newcorporder/match/companyAbility/GuerillaMarketingAbility.java
Con dos "R"

2023-11-02 17:18 UTC, mimbrero approved these changes

2023-11-02 17:19 UTC, MarcoAnarmo approved these changes
Todo oki🥰🥰

2023-11-02 17:22 UTC, merged