Create users module classes
gii-is-DP1/new-corp-order-l2-1 pull request #49
Opened 2023-10-28 17:35 UTC by VictoriaCRD

2023-10-30 11:46 UTC, mimbrero requested changes
Haz `Ctrl + Alt + L` en todas las clases que hagas para que IntelliJ te formatee el código de la forma que estamos siguiendo en el proyecto.

2023-10-30 11:46 UTC, mimbrero commented on src/main/java/us/lsi/dp1/newcorporder/player/Players.java
Esta clase no tiene sentido, ya está el `PlayerRepository` y en `Match` controlamos los `MatchPlayer`s. Bórrala

2023-10-30 11:46 UTC, mimbrero commented on src/main/java/us/lsi/dp1/newcorporder/player/Player.java
> +public class Player extends BaseEntity {
Deja una línea en blanco para separar las declaraciones de clases, separar funciones, entre los imports y la clase...

2023-10-30 11:46 UTC, mimbrero commented on src/main/java/us/lsi/dp1/newcorporder/player/Player.java
> +
Deja solo una línea

2023-10-30 11:46 UTC, mimbrero commented on src/main/java/us/lsi/dp1/newcorporder/player/Player.java
> +
Deja solo una línea

2023-10-30 11:46 UTC, mimbrero commented on src/main/java/us/lsi/dp1/newcorporder/player/Player.java
> +    public static Player createDefault() {
Este método es innecesario, bórralo

2023-10-30 11:46 UTC, mimbrero commented on src/main/java/us/lsi/dp1/newcorporder/player/PlayerRepository.java
> +    @Query("SELECT p FROM Player p")
La query no hace falta ponerla, Spring sabe interpretar el nombre del método y genera la query él solo. Borra la anotación.

2023-10-30 11:46 UTC, mimbrero commented on src/main/java/us/lsi/dp1/newcorporder/player/PlayerRepository.java
> +
Deja solo una línea en blanco

2023-10-30 11:46 UTC, mimbrero commented on src/main/java/us/lsi/dp1/newcorporder/player/PlayerService.java
Controla las líneas en blanco para que tenga cohesión con el resto del proyecto :)

2023-11-23 16:12 UTC, MarcoAnarmo requested changes
El commit ponlo con la etiqueta fix

2023-11-23 16:12 UTC, MarcoAnarmo commented on src/main/java/us/lsi/dp1/newcorporder/player/Player.java
> +}
'Player' no tiene estos atributos, los tiene 'User', lo puedes comprobar en el modelo conceptual de la carpeta de Drive. Entonces, pasa los atributos a 'User', pero deja la clase 'Player' (vacía).

2023-11-23 16:12 UTC, MarcoAnarmo commented on src/main/java/us/lsi/dp1/newcorporder/player/Player.java
'Player' tiene que tener una relación one to one con 'User', puedes verlo en el diagrama conceptual.

2023-11-25 09:02 UTC, MarcoAnarmo submitted a review, later dismissed
Todo oki👍🏿

2023-11-25 09:05 UTC, MarcoAnarmo approved these changes

2023-11-25 13:08 UTC, merged